#define DYNAMIC_KEYMAP_LAYER_COUNT 4
#define USB_POLLING_INTERVAL_MS 1
#define RGBLIGHT_DEFAULT_ON true
#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_RAINBOW_SWIRL + 5
#define HOLD_ON_OTHER_KEY_PRESS
#define TAP_CODE_DELAY 25
#define TAP_HOLD_CAPS_DELAY 25
#define WS2812_DI_PIN GP24
#define LED_CAPS_LOCK_PIN GP13
