#define WS2812_DI_PIN GP13
#define RGBLIGHT_DEFAULT_ON false
#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_RAINBOW_SWIRL + 5
#define RP2040_FLASH_GENERIC_03H
#define EXTERNAL_FLASH_BYTE_COUNT 524288 // 4Mb
#define PS2_PIO_USE_PIO1