ANALOG_DRIVER_REQUIRED = yes
WS2812_DRIVER = vendor
CUSTOM_MATRIX = yes
SRC += mv_main.c
CONSOLE_ENABLE = yes

LTO_ENABLE = yes
SPLIT_KEYBOARD = no

COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
NKRO_ENABLE = no
SLEEP_LED_ENABLE = no
BACKLIGHT_ENABLE = no
UNICODE_ENABLE = no
SWAP_HANDS_ENABLE = no