#pragma once

#define RP2040_FLASH_GENERIC_03H
#define EXTERNAL_FLASH_BYTE_COUNT 524288 // 4Mb
#define USB_POLLING_INTERVAL_MS 1
#define HOLD_ON_OTHER_KEY_PRESS
#define TAP_CODE_DELAY 25
#define TAP_HOLD_CAPS_DELAY 25
#define DYNAMIC_KEYMAP_LAYER_COUNT 8
#define DEBOUNCE 15
