#pragma once

#define RP2040_FLASH_GENERIC_03H
#define EXTERNAL_FLASH_BYTE_COUNT 524288 // 4Mb
#define USB_POLLING_INTERVAL_MS 1
#define DEBOUNCE 15
#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_RAINBOW_SWIRL + 5