#define RP2040_FLASH_GENERIC_03H
#define EXTERNAL_FLASH_BYTE_COUNT 524288 // 4Mb
#define USB_POLLING_INTERVAL_MS 1
#define DEBOUNCE 0
#define ADC_BUFFER_DEPTH 1
#define HOLD_ON_OTHER_KEY_PRESS
#define TAP_CODE_DELAY 25
#define TAP_HOLD_CAPS_DELAY 25
#define DYNAMIC_KEYMAP_LAYER_COUNT 6
#define VIA_EEPROM_CUSTOM_CONFIG_SIZE 150
#define WS2812_DI_PIN GP13
#define RGBLIGHT_DEFAULT_ON false
#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_RAINBOW_SWIRL + 5
#define JOYSTICK_AXIS_COUNT 6
#define JOYSTICK_BUTTON_COUNT 12
#define MIDI_ADVANCED
//#define COUNT_SCANS
