#define VIA_EEPROM_CUSTOM_CONFIG_SIZE 142
#define HOLD_ON_OTHER_KEY_PRESS
#define WS2812_DI_PIN GP13
#define RGBLIGHT_DEFAULT_ON false
#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_ALTERNATING
#define JOYSTICK_AXIS_COUNT 6
#define JOYSTICK_BUTTON_COUNT 12
#define MIDI_ADVANCED
